version: '3'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
  #  depends_on:
  #    - focus-frontend

  # frontend:
  #   image: focus-frontend
  #   ports:
  #    - "80:80"