version: '3'

services:
  backend:
    build: ./backend
    ports: ["5000:5000"]
    env_file:
      - .env
    volumes: ['./backend:/backend']
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports: ["3000:3000"]
    volumes: ['./frontend:/frontend']