apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: chengmingli/backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-env
