apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: chengmingli/frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-env
