apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: chengmingli/website:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-env
